name: BigQuery Cloud Integration Testing
on:
  push:
    branches:
    - 'terraform-it'

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/test/resources/terraform

    steps:
      - name: Set GCP environment
        id: set_gcp_env
        run: echo ::set-env name=BRANCH_NAME::$(echo ${GITHUB_BASE_REF#refs/heads/})

      - uses: actions/checkout@v3

      - name: configure auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/263903559714/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-provider'
          service_account: 'gh-bq-deployer@gh-integration-tests.iam.gserviceaccount.com'

      - name: set GCP project
        id: config_project
        run: gcloud config set project gh-integration-tests

      - name: "Terraform Init"
        id: terraform_init
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: environments/${{ env.BRANCH_NAME }}
          tf_actions_subcommand: init

      - name: "Terraform Validate"
        id: terraform_validate
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: environments/${{ env.BRANCH_NAME }}
          tf_actions_subcommand: validate

      - name: "Terraform Plan"
        id: terraform_plan
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: environments/${{ env.BRANCH_NAME }}
          tf_actions_subcommand: plan

      - name: "Terraform Apply"
        uses: ops18/terraform-github-actions@master
        id: terraform_apply
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: environments/${{ env.BRANCH_NAME }}
          tf_actions_subcommand: apply

  test:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: BigQuery Test Run
        run: mvn -Dtest=LiquibaseHarnessSuiteTest -DconfigFile=/harness-config-it.yml test

      - name: Archive Bigquery Database Test Results
        uses: actions/upload-artifact@v3
        with:
          name: bigquery-test-results
          path: build/spock-reports

  destroy:
    runs-on: ubuntu-latest
    needs: [setup,test]
    defaults:
      run:
        working-directory: src/test/resources/terraform
    if: ${{ always() }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve