name: BigQuery Cloud Integration Testing
on:
  push:
    branches:
    - 'terraform-it'
env:
  tf_version: 'latest'

jobs:
  setup:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: configure auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/263903559714/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-provider'
          service_account: 'gh-bq-deployer@gh-integration-tests.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: set GCP project
        id: config_project
        run: gcloud config set project gh-integration-tests

      - name: "Terraform Init"
        id: terraform_init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          TF_ACTION_WORKING_DIR: src/test/resources/terraform

      - name: "Terraform Validate"
        id: terraform_validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7
        env:
          TF_ACTION_WORKING_DIR: src/test/resources/terraform

      - name: "Terraform Apply"
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        id: terraform_apply
        env:
          TF_ACTION_WORKING_DIR: src/test/resources/terraform

  test:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: BigQuery Test Run
        run: mvn -Dtest=LiquibaseHarnessSuiteTest -DconfigFile=/harness-config-it.yml test

      - name: Archive Bigquery Database Test Results
        uses: actions/upload-artifact@v3
        with:
          name: bigquery-test-results
          path: build/spock-reports

  destroy:
    runs-on: ubuntu-latest
    needs: [setup,test]
    defaults:
      run:
        working-directory: src/test/resources/terraform

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve